# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "http://jagarela.github.io/kokpit"

# The name of this wonderful theme ;-).
theme = "mouse-bear"

# Basic metadata configuration for your blog.
title = "Kokpit"
author = "ğŸ­"
languageCode = "pl-PL"

[params]
  favicon = "media/favicon.png"

  # This is used in the meta data of your generated html.
  description = "ğŸ­ + ğŸ¹ = â¤ï¸"

  # This one is used as the site_name on the Hugo's internal opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "mysz"

  # See [Hugo's Format function docs](https://gohugo.io/functions/format/) for details.
  dateFormat = "02-01-2006"

  # Custom stylesheets to include from /static/styles directory
  stylesheets = [ ]
  # Custom scripts to include from /static/scripts directory
  scripts = []